#Define colors
phyla.col <- c("Acidimicrobiia"="#AA4488",
               "Actinobacteria" = "#DDAA77",
               "Alphaproteobacteria"= "#771155",
               "Bacilli"="#117744", 
               "Bacteroidia"= "#77AADD",
               "Campylobacteria" = "#FF2222",
               #"Chlamydiae"= "#DD1232" ,
               #"Clostridia"= "#77CCCC", 
               "Cyanobacteriia"= "#AAAA44",
               "Clostridia" ="#CC1234", 
               #"Desulfobulbia"= "#117744", 
               "Gammaproteobacteria"="#117777",
               "Gracilibacteria"= "#44AA77",
               "Kiritimatiellae" = "#DD7788",
               "Negativicutes"= "#34ABAA", 
               "Paracubacteria"= "#11BBCC", 
               #"NB1-j_uncl" = "#774411",
               #"Nitrososphaeria" = "#E69F00",
               "Parcubacteria"= "#88CCAA", 
               "Planctomycetes"= "#777711",
               #"OM190"= "#009E73",
               #"SAR324_clade(Marine_group_B)_uncl"="#CC99BB",
               "Saccharimonadia" = "#AACC45",
               #"Thermoplasmata" = "#0072B2",
               "Verrucomicrobiae" = "#AA7744",
               #"Vicinamibacteria" ="#DDDD77",
               "Other taxa"= "#114477")

saveRDS(phyla.col, "./data/phyla_col.RDS")

indicators.col <- c("Aeromonadaceae"="#AA4488",
                    "Arcobacteraceae" = "#771155",
                    "Bacteroidaceae"= "#DDAA77",
                    "Bdellovibrionaceae"="#117744", 
                    "Carnobacteriaceae"= "#77AADD",
                    "Campylobacteraceae" = "#FF2222",
                    "Chlamydiaceae"= "#DD1232" ,
                    "Enterococcaceae"= "#77CCCC", 
                    "Clostridiaceae" ="#CC1234", 
                    "Desulfovibrionaceae"= "#117744", 
                    "Enterobacteriaceae"="#117777",
                    "Flavobacteriaceae"= "#44AA77",
                    "Helicobacteraceae" = "#DD7788",
                    "Lachnospiraceae"= "#34ABAA", 
                    "Legionellaceae"= "#11BBCC", 
                    "Leptospiraceae" = "#774411",
                    "Listeriaceae" = "#E69F00",
                    "Moraxellaceae"= "#88CCAA", 
                    "Mycobacteriaceae"= "#777711",
                    "Porphyromonadaceae"= "#009E73",
                    "Pseudomonadaceae"="#CC99BB",
                    "Ruminococcaceae" = "#AACC45",
                    "Staphylococcaceae" = "#0072B2",
                    "Streptococcaceae" = "#AA7744",
                    "Vibrionaceae" ="#DDDD77",
                    "Yersiniaceae"= "#AAAA44",
                    "Other taxa"= "#114477")

saveRDS(indicators.col, "./data/indicators_col.RDS")
