
#Define colors
phyla.col <- c("Acidimicrobiia"="#AA4488",
               "Actinobacteria" = "#DDAA77",
               "Alphaproteobacteria"= "#771155",
               "Bacilli"="#117744", 
               "Bacteroidia"= "#77AADD",
               "Campylobacteria" = "#FF2222",
               #"Chlamydiae"= "#DD1232" ,
               #"Clostridia"= "#77CCCC", 
               "Cyanobacteriia"= "#AAAA44",
               "Clostridia" ="#CC1234", 
               #"Desulfobulbia"= "#117744", 
               "Gammaproteobacteria"="#117777",
               "Gracilibacteria"= "#44AA77",
               "Kiritimatiellae" = "#DD7788",
               "Negativicutes"= "#34ABAA", 
               "Paracubacteria"= "#11BBCC", 
               #"NB1-j_uncl" = "#774411",
               "Rhodothermia" = "#E69F00",
               "Parcubacteria"= "#88CCAA", 
               "Planctomycetes"= "#777711",
               #"OM190"= "#009E73",
               #"SAR324_clade(Marine_group_B)_uncl"="#CC99BB",
               "Saccharimonadia" = "#AACC45",
               #"Thermoplasmata" = "#0072B2",
               "Verrucomicrobiae" = "#AA7744",
               #"Vicinamibacteria" ="#DDDD77",
               "Other taxa"= "#114477")

indicators.col <- c("Aeromonadaceae"="#AA4488",
                    "Arcobacteraceae" = "#771155",
                    "Bacteroidaceae"= "#DDAA77",
                    "Bdellovibrionaceae"="#AAAA44", 
                    "Carnobacteriaceae"= "#77AADD",
                    "Campylobacteraceae" = "#FF2222",
                    "Chlamydiaceae"= "#E5C494" ,
                    "Enterococcaceae"= "#117777", 
                    "Clostridiaceae" ="#CC1234", 
                    "Desulfovibrionaceae"= "#117744", 
                    "Enterobacteriaceae"="#77CCCC",
                    "Flavobacteriaceae"= "#44AA77",
                    "Helicobacteraceae" = "#88CCAA",
                    "Lachnospiraceae"= "#34ABAA", 
                    "Legionellaceae"= "#11BBCC", 
                    "Leptospiraceae" = "#774411",
                    "Listeriaceae" = "#E69F00",
                    "Moraxellaceae"= "#DDDD77", 
                    "Mycobacteriaceae"= "#777711",
                    "Porphyromonadaceae"= "#009E73",
                    "Pseudomonadaceae"="#CC99BB",
                    "Ruminococcaceae" = "#AACC45",
                    "Staphylococcaceae" = "#0072B2",
                    "Streptococcaceae" = "#AA7744",
                    "Vibrionaceae" = "#DD7788",
                    "Yersiniaceae"= "#117744",
                    "Other taxa"= "#114477")

location.col <- c("R-Estuary-1" = "#FC8D62", 
                  "R-Estuary-2" = "#FFD92F", 
                  "NS-Marine" = "#E5C494", 
                  "OS-Marine" = "#8DA0CB",
                  "SM-Outfall" = "#66C2A5", 
                  "R-Mouth" = "#E41A1C")

season.col <- c("winter" = "#377EB8", 
                "spring" = "#4cbb30", 
                "summer" = "#E41A1C", 
                "autumn" = "#A65628")

tol21rainbow<- c("#771155",
                 "#AA4488",
                 "#CC99BB",
                 "#114477", 
                 "#4477AA",
                 "#117744",
                 "#117777",
                 "#88CCAA", 
                 "#77CCCC",
                 "#00ffff",
                 "#44AA77",
                 "#44AAAA", 
                 "#777711",
                 "#AAAA44",
                 "#DDDD77",
                 "#774411", 
                 "#AA7744",
                 "#DDAA77",
                 "#771122",
                 "#AA4455", 
                 "#DD7788")
